#!/bin/bash
# Reddit Skill 快速配置

echo "🚀 Reddit Skill 安装完成！"
echo ""
echo "📦 安装位置: /root/.openclaw/workspace/skills/reddit-skill/"
echo ""
echo "⚠️  需要配置 Reddit API 凭证才能使用"
echo ""
echo "📋 配置步骤:"
echo ""
echo "1️⃣  获取 Reddit API 凭证:"
echo "   访问: https://www.reddit.com/prefs/apps"
echo "   点击: 'create another app...'"
echo "   选择: script 类型"
echo "   填写: Name = 'OpenClaw Reddit'"
echo "   填写: Redirect URI = http://localhost:8080"
echo "   记录: client_id 和 client_secret"
echo ""
echo "2️⃣  设置环境变量:"
echo "   export REDDIT_CLIENT_ID='your_client_id'"
echo "   export REDDIT_CLIENT_SECRET='your_client_secret'"
echo ""
echo "3️⃣  或者创建 .env 文件:"
echo "   cd /root/.openclaw/workspace/skills/reddit-skill"
echo "   cat > .env << EOF"
echo "   REDDIT_CLIENT_ID=your_client_id"
echo "   REDDIT_CLIENT_SECRET=your_client_secret"
echo "   EOF"
echo ""
echo "🎯 使用方法:"
echo "   python3 scripts/reddit_reader.py search 'Claude Code' --sort hot"
echo "   python3 scripts/reddit_reader.py list r/ClaudeAI --category top"
echo "   python3 scripts/reddit_reader.py read 'https://reddit.com/r/...'"
echo ""
echo "💡 在 OpenClaw 中使用:"
echo "   '搜索 Reddit 上关于 AI Agent 的讨论'"
echo "   '看看 r/ClaudeAI 最近有什么热帖'"
echo ""
