#!/bin/bash
# 小红书运营 Skill 快速启动

echo "🚀 小红书运营 Skill (xiaohongshu-ops)"
echo ""
echo "📦 安装位置: /root/.openclaw/workspace/skills/xiaohongshu-ops/"
echo ""
echo "✅ 核心能力:"
echo "   • 账号定位与内容方向"
echo "   • 选题产出与爆款挖掘"
echo "   • 小红书发布流程"
echo "   • 评论互动 / 自动回复"
echo "   • 数据复盘"
echo ""
echo "📱 飞书集成:"
echo "   通过飞书下发运营指令，手机也能随时控制"
echo ""
echo "🎯 使用方法:"
echo ""
echo "1. 阅读 SKILL.md 了解完整流程"
echo "   less /root/.openclaw/workspace/skills/xiaohongshu-ops/SKILL.md"
echo ""
echo "2. 查看 SOUL.md 了解人设语气"
echo "   cat /root/.openclaw/workspace/skills/xiaohongshu-ops/SOUL.md"
echo ""
echo "3. 在 OpenClaw 中使用:"
echo "   直接输入指令，如:"
echo "   • '帮我制定小红书账号定位'"
echo "   • '生成一个爆款选题'"
echo "   • '写一篇小红书笔记关于 AI Agents'"
echo ""
echo "⚠️  注意:"
echo "   需要先在浏览器登录小红书创作后台:"
echo "   https://creator.xiaohongshu.com"
echo ""
echo "📚 参考案例:"
echo "   examples/drama-watch/case.md - 陪你看剧实例"
echo ""
